# Generated by Django 4.0.3 on 2022-04-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_comment_comment_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_maker',
            field=models.CharField(default='', max_length=100),
        ),
    ]
