# Generated by Django 4.0.3 on 2022-04-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_comment_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_answer',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
