# Generated by Django 4.0.3 on 2022-04-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_feedback_feedback_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback_email_asker',
            new_name='feedback_username',
        ),
    ]
